name: in_app_update
description: Enables In App Updates on Android using the official Android APIs.
version: 1.1.2
authors:
- FFUF <info@ffuf.de>
- Jonas Bark <jonas.bark@ffuf.de>
homepage: https://ffuf.de
repository: https://github.com/feilfeilundfeil/flutter_in_app_update

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_plugin_android_lifecycle: ^1.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: de.ffuf.in_app_update
    pluginClass: InAppUpdatePlugin